// ! THIS FILE IS AUTOMATICALLY GENERATED. DO NOT CHANGE.
/** Endpoints tagged "paginated" in openAPI schema. */
export type PaginatedOperationId = "getUsers"
|"getRooms"
|"getRoomsByUserId"
|"getFriendships"
|"getLikesByUserId"
|"getCommentsByRoomId"
|"getLikesByRoomId";
